spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sykn
    username: root
    password: mysql
    
  batch:
    initialize-schema: always
    job:
      enabled: false
 
mybatis:
  configuration:
    map-underscore-to-camel-case: true   
